#!/usr/bin/env python3
"""Prepare a project tooling shell; never provision or send mail."""
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
TERRAFORM_ROOTS = (
    "terraform/bootstrap", "terraform/modules/receiver",
    "terraform/examples/cloudflare", "terraform/examples/route53",
    "terraform/examples/manual",
)


def environment(root):
    env = dict(os.environ)
    directories = [root / ".dev-tools/bin", root / ".dev-tools/venv/bin",
                   root / ".dev-tools/tfenv/bin", root / "node_modules/.bin"]
    env["PATH"] = os.pathsep.join(map(str, directories)) + os.pathsep + env.get("PATH", "")
    env["PLAYWRIGHT_BROWSERS_PATH"] = str(root / ".dev-tools/browsers")
    env["HAIL_LIVE"] = "0"
    return env


def run(command, root):
    subprocess.run(command, cwd=root, env=environment(root), check=True)


def missing_tools(root):
    env = environment(root)
    missing = [tool for tool in ("git", "node", "npm", "terraform", "tfenv", "tflint", "trivy", "gitleaks", "pre-commit")
               if not shutil.which(tool, path=env["PATH"])]
    if sys.version_info < (3, 12):
        missing.append("Python >=3.12")
    if "node" not in missing:
        result = subprocess.run(["node", "-p", "process.versions.node.split('.')[0]"], env=env, capture_output=True, text=True)
        if result.returncode or not result.stdout.strip().isdigit() or int(result.stdout) < 22:
            missing.append("node >=22")
    version_file = root / ".terraform-version"
    if "terraform" not in missing and version_file.exists():
        result = subprocess.run(["terraform", "version", "-json"], env=env, capture_output=True, text=True)
        import json
        try:
            installed = json.loads(result.stdout)["terraform_version"]
        except (ValueError, KeyError):
            installed = None
        if result.returncode or installed != version_file.read_text().strip():
            missing.append("Terraform " + version_file.read_text().strip())
    for tool in ("tsc", "tsx", "eslint", "prettier", "playwright"):
        if not (root / "node_modules/.bin" / tool).exists():
            missing.append("npm dependency: " + tool)
    if "node" not in missing and (root / "node_modules/@playwright/test").exists():
        browser_check = subprocess.run(
            ["node", "--input-type=module", "-e", 'import {chromium, firefox, webkit} from "@playwright/test"; import {existsSync} from "node:fs"; process.exit([chromium, firefox, webkit].every(b => existsSync(b.executablePath())) ? 0 : 1)'],
            cwd=root, env=env, capture_output=True, text=True)
        if browser_check.returncode:
            missing.append("Playwright browsers")
    return missing


def require_tools(root):
    missing = missing_tools(root)
    if missing:
        print("Missing or incompatible development tools: " + ", ".join(missing) + ".\nRun make deps, then make setup.", file=sys.stderr)
        return False
    return True


def write_activation(root):
    destination = root / ".dev-tools/activate"
    destination.parent.mkdir(parents=True, exist_ok=True)
    paths = ":".join(str(root / p) for p in (".dev-tools/bin", ".dev-tools/venv/bin", ".dev-tools/tfenv/bin", "node_modules/.bin"))
    destination.write_text("# Generated by make setup; source this file in Bash or Zsh.\n"
                           + "export HAIL_DEV_ROOT=" + shlex.quote(str(root)) + "\n"
                           + "export PLAYWRIGHT_BROWSERS_PATH=" + shlex.quote(str(root / ".dev-tools/browsers")) + "\n"
                           + "export PATH=" + shlex.quote(paths) + ':"$PATH"\n')
    return destination


def setup(root):
    if not require_tools(root):
        return 1
    run(["npm", "ci"], root)
    run(["npm", "run", "build"], root)
    run(["tflint", "--init"], root)
    for directory in TERRAFORM_ROOTS:
        run(["terraform", "-chdir=" + directory, "init", "-backend=false", "-lockfile=readonly"], root)
    run(["pre-commit", "install"], root)
    run(["pre-commit", "install", "--hook-type", "pre-push"], root)
    destination = write_activation(root)
    print("Development setup ready. Activate this shell with:\n  source " + shlex.quote(str(destination)) + "\nOr run make shell.")
    return 0


def check(root):
    if not require_tools(root):
        return 1
    for script in ("build", "lint", "prettier", "typecheck", "test", "test:coverage", "test:python", "test:e2e", "test:package"):
        run(["npm", "run", script], root)
    run(["terraform", "fmt", "-check", "-recursive", "terraform"], root)
    run(["tflint", "--init"], root)
    run(["tflint", "--chdir=terraform", "--recursive", "--config=" + str(root / ".tflint.hcl")], root)
    run(["trivy", "config", "--exit-code", "1", "--severity", "HIGH,CRITICAL", "--ignorefile", ".trivyignore.yaml", "terraform"], root)
    for directory in TERRAFORM_ROOTS:
        for arguments in (("init", "-backend=false", "-lockfile=readonly"), ("validate",), ("test",)):
            run(["terraform", "-chdir=" + directory, *arguments], root)
    return 0


if __name__ == "__main__":
    try:
        if len(sys.argv) != 2 or sys.argv[1] not in ("setup", "check"):
            raise SystemExit("Usage: scripts/dev.py {setup|check}")
        raise SystemExit({"setup": setup, "check": check}[sys.argv[1]](ROOT))
    except subprocess.CalledProcessError as error:
        print("Development command failed: " + shlex.join(error.cmd), file=sys.stderr)
        raise SystemExit(error.returncode)
